### PR TITLE
Avoid empty error messages

### LINKED ISSUE #41: Some errors result in useless messages printed to the user
I executed a few thousand simultaneous jobs yesterday and saw some of them fail with the error:

   starting pipeline: "": ""

which seems to imply that the server replied with a google API error with no message or code.  I presume it was a quota violation (QPS limit exceeded for example).  I think we can just drop the specialized API error handling and print the standard error message (the API error was useful for internal debugging, but otherwise not helpful).

### PR DESCRIPTION
**Pull request by anamanolache**
This fixes #41

### CODE REVIEW

File: pipelines/internal/commands/run/run.go [hunk 1]
```diff
@@ -207,7 +207,7 @@ func runPipeline(ctx context.Context, service *genomics.Service, req *genomics.R
 
 		lro, err := service.Pipelines.Run(req).Context(ctx).Do()
 		if err != nil {
-			if err, ok := err.(*googleapi.Error); ok {
+			if err, ok := err.(*googleapi.Error); ok && err.Message != "" {
```
Comment (anamanolache) [inline pipelines/internal/commands/run/run.go]: They will probably both be nill of non nill but even is the body is nill and the message is not it would be worth printing out the message instead of the plain error.
